name: deep5_notifications
description: A push notification service which uses OneSignal as push notification provider.
repository: https://github.com/deep5-io/deep5_notifications
issue_tracker: https://github.com/deep5-io/deep5_notifications/issues
homepage: https://github.com/deep5-io/deep5_notifications
documentation: https://github.com/deep5-io/deep5_notifications

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  onesignal_flutter: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
